# Settings file for configure.pyz.
#
# Relative paths are searched from the directory from within configure.pyz is
# called.
#
# $rootpath is also available in this file, it expands to the full path of the
# calling directory.

variables:
  project_name:   MESS Engine
  sourcedir:      source
  builddir:       build
  projectsdir:    projects

compiler:
  cxx:      clang++
  cflags:   -std=c++1z -pthread -Wall -Wextra
  lflags:   -pthread -Wall -Wextra -L$builddir/crypto/install/lib
  includes: [$sourcedir, $builddir/crypto/install/include, /usr/include/python3.5m]
  defines:  []

configurations:
  - name: release
    bin:  $builddir/mess/release/bin
    lib:  $builddir/mess/release/lib
    obj:  $builddir/mess/release/obj
    cflags:  -O3
    defines: [NDEBUG]
  - name: debug
    bin:  $builddir/mess/debug/bin
    lib:  $builddir/mess/debug/lib
    obj:  $builddir/mess/debug/obj
    cflags:  -O0 -g
    defines: [_DEBUG]

targets:
  filename: targets.yaml
  defaults:
    type:          static_library
    dependencies:  []
    defines:       []
    include_dirs:  []
    sources:       ["*.cpp", "*.cc"]
    headers:       ["*.hpp", "*.h"]
    embedded_data: []
    unused:        []

ninja:
  filename: build.ninja
  add_default_rules: true
  include_file: null

makefile:
  filename: Makefile

doxygen:
  doxyfile_template: null

sublime:
  project_template: null

codeblocks:
  compiler_name: clang
